variables:
  - production_realised
  - final_demand_unmet

step_to_eq: 1825
inv_sce:
  - "90-60"
  - "9-6"
MRIOT:
  - "OECD21-2018"

rebuild_tau : 365
duration: 3
order_type: "noalt"
alpha_max: 1
alpha_tau: 365
psi: 0.80
monetary_factor: 1000000
