variables:
  - production_realised
  - final_demand_unmet
  - rebuild_demand
  - overproduction
  - intermediate_demand
  - limiting_inputs

step_to_eq: 1825
inv_sce:
  - "90-60"
  - "9-6"
MRIOT:
  - "EXIOBASE3-2010"

rebuild_tau : 365
duration: 3
order_type: "alt"
alpha_tau: 365
psi: 0.80
monetary_factor: 100000
